-- Câu 1
select MANV,HONV,TENLOT,TENNV,PHONG
from NHANVIEN
where PHONG='NC';

-- Câu 2
select MANV,HONV,TENLOT,TENNV,PHAI,MLUONG
from NHANVIEN
where MLUONG >= 3000000;

-- Câu 3
select HONV,TENLOT,TENNV,TENPHG,MLUONG
from NHANVIEN NV join PHONGBAN PB on NV.PHONG=PB.MAPHG
where MLUONG between 2000000 and 3000000;

-- Câu 4
select HONV,TENNV,TENNV,DCHI 
from NHANVIEN 
where DCHI like '%TP HCM%'

-- Câu 5
select HONV,TENLOT,TENNV,NGSINH,DCHI
from NHANVIEN
where HONV+TENLOT+TENNV = 'DinhBaTien';

-- Câu 6
select MATN,TENTN,TN.NGSINH
from NHANVIEN NV join THANNHAN TN on TN.MANV=NV.MANV
where NV.MANV='003' and year(getdate()) - year(TN.NGSINH) < 40;

-- Câu 7
select HONV,TENNV,PHAI
from NHANVIEN
where PHAI='Nu' and year(getdate()) - year(NGSINH) > 30;

-- Câu 8
select TENPHG,DIADIEM,PB.MAPHG
from PHONGBAN PB join DDIEM_PHG DD on PB.MAPHG=DD.MAPHG

-- Câu 9 
select HONV,TENLOT,TENNV
from PHONGBAN PB join NHANVIEN NV on PB.TRPHG=NV.MANV 

-- Câu 10
select TENDA, MADA, DDIEM_DA, TENPHG, PB.MAPHG, TRPHG, NGNC
from DEAN DA join PHONGBAN PB on DA.MAPHG=PB.MAPHG

-- Câu 11
select HONV,TENLOT,TENNV,PHONG,TENPHG
from NHANVIEN NV join PHONGBAN PB on NV.PHONG=PB.MAPHG
where TENPHG='Nghien cuu'

-- Câu 12
select HONV,TENLOT,TENNV,TENTN
from NHANVIEN NV join THANNHAN TN on NV.MANV=TN.MANV
where NV.PHAI='Nu' 

-- Câu 13
select NV.MANV,HONV,TENLOT,TENNV,TENPHG,TENDA
from NHANVIEN NV join PHONGBAN PB on NV.PHONG = PB.MAPHG join PHANCONG PC on PC.MANV=NV.MANV join DEAN DA on DA.MADA=PC.MADA
where PB.TENPHG='Nghien cuu' and TENDA like '%Tin hoc hoa%'

-- Câu 14
select MADA,DA.MAPHG,HONV,TENLOT,TENNV,DCHI,NGSINH,DA.DDIEM_DA
from DEAN DA join PHONGBAN PB on DA.MAPHG=PB.MAPHG join NHANVIEN NV on NV.MANV=PB.TRPHG
where DA.DDIEM_DA = 'HaNoi'

-- Câu 15
select  NV1.MANV,NV1.HONV,NV1.TENLOT,NV1.TENNV,NV2.HONV + ' ' + NV2.TENLOT + ' ' + NV2.TENNV as 'NGUOI QUAN LY'
from NHANVIEN NV1 join NHANVIEN NV2 on NV1.MA_NQL=NV2.MANV

-- Câu 16
select NV1.HONV,NV1.TENLOT,NV1.TENNV,NV2.HONV + ' ' + NV2.TENLOT + ' ' + NV2.TENNV as 'TRUONG PHONG'
from NHANVIEN NV1 join (NHANVIEN NV2 join PHONGBAN PB on NV2.MANV=PB.TRPHG) on NV1.PHONG=PB.MAPHG

-- Câu 17
select *
from NHANVIEN NV left join PHANCONG PC on NV.MANV=PC.MANV left join DEAN DA on DA.MADA=PC.MADA


