version: '3.8'

services:
  # Căn nhà số 1: Lưu trữ dữ liệu (Đã cấu hình giữ lại dữ liệu an toàn)
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: my_db
    volumes:
      # Dấu ../ nghĩa là đi lùi ra ngoài thư mục Systemhospital, tìm đúng folder Docker_Data
      # và tạo một thư mục con tên là 'postgres_data' để lưu dữ liệu database vào đó.
      - ../Docker_Data/postgres_data:/var/lib/postgresql/data

  # Căn nhà số 2: Bộ nhớ đệm (làm mượt hệ thống)
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    # Redis là bộ nhớ đệm tạm thời nên thường không cần lưu volume ra ngoài máy thật.

  # Căn nhà số 3: Hệ thống xếp hàng tin nhắn
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
