spring.application.name=backend
# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/mcn_db
spring.datasource.username=admin
spring.datasource.password=mcn12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Dev mode
app.dev-mode=true