import os                                                                                                                                                                                                                                                                                                         
from fastapi import APIRouter                                                                                                                                                                                                                                                                                     
from pydantic import BaseModel                                                                                                                                                                                                                                                                                    
from groq import Groq                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                    
router = APIRouter(prefix="/ai", tags=["AI Suggest"])                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                    
GROQ_API_KEY = os.getenv("GROQ_API_KEY")                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                    
DEPARTMENTS = [
"Nội Tiêu Hóa", "Nội Khoa", "Nội Tim Mạch",                                                                                                                                                                                                                                                                   
      "Tai Mũi Họng", "Xương Khớp", "Ngoại Khoa",
      "Da Liễu", "Mắt", "Thần Kinh"           
  ]                                           
                                                                                                                                                                                                                                                                                                                    
KEYWORDS = {                                                                                                                                                                                                                                                                                                      
      "Nội Tiêu Hóa": ["bụng","tiêu chảy","buồn nôn","nôn","dạ dày","táo bón","trào ngược"],                                                                                                                                                                                                                        
      "Nội Tim Mạch": ["tim","ngực","huyết áp","nhịp tim","khó thở","đánh trống ngực"],                                                                                                                                                                                                                             
      "Tai Mũi Họng": ["tai","mũi","họng","ho","viêm","nghẹt mũi","đau họng"],                                                                                                                                                                                                                                      
      "Xương Khớp":   ["khớp","xương","lưng","cổ","vai","tê","đau nhức"],
      "Da Liễu":      ["da","mụn","ngứa","phát ban","dị ứng","nổi mề đay"],                                                                                                                                                                                                                                         
      "Mắt":          ["mắt","mờ","đỏ mắt","chảy nước mắt","nhìn"],
"Thần Kinh":    ["đầu","chóng mặt","mất ngủ","tê liệt","co giật","stress"],                                                                                                                                                                                                                                   
      "Ngoại Khoa":   ["vết thương","phẫu thuật","u","khối","sưng"],                                                                                                                                                                                                                                                
      "Nội Khoa":     ["sốt","mệt","yếu","chán ăn","sụt cân"],                                                                                                                                                                                                                                                      
  }                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                    
def keyword_fallback(text: str):                                                                                                                                                                                                                                                                                  
      text_lower = text.lower()                                                                                                                                                                                                                                                                                     
      scores = {}                                                                                                                                                                                                                                                                                                   
      for dept, keys in KEYWORDS.items():
        scores[dept] = sum(1 for k in keys if k in text_lower)                                                                                                                                                                                                                                                    
      sorted_depts = sorted(scores.items(), key=lambda x: x[1], reverse=True)
      results = []                                                                                                                                                                                                                                                                                                  
      for dept, score in sorted_depts[:3]:
          results.append({"department": dept, "confidence": round(min(score * 0.25, 0.95), 2)})                                                                                                                                                                                                                     
      if not results[0]["confidence"]:                                                                                                                                                                                                                                                                              
          results[0] = {"department": "Nội Khoa", "confidence": 0.5}
      return results                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    
class SuggestRequest(BaseModel):
      text: str                                                                                                                                                                                                                                                                                                     
                  
@router.post("/suggest-department")                                                                                                                                                                                                                                                                               
def suggest_department(req: SuggestRequest):
      if not GROQ_API_KEY or not req.text.strip():
        return {"suggested_departments": keyword_fallback(req.text)}                                                                                                                                                                                                                                              
      try:                                
          client = Groq(api_key=GROQ_API_KEY)                                                                                                                                                                                                                                                                       
          prompt = f"""Bệnh nhân mô tả: "{req.text}"                                                                                                                                                                                                                                                                
  Danh sách khoa: {', '.join(DEPARTMENTS)}    
  Trả về JSON (chỉ JSON, không giải thích):                                                                                                                                                                                                                                                                         
  {{"suggested_departments": [{{"department": "...", "confidence": 0.0}}]}}                                                                                                                                                                                                                                         
  Chọn top 3 khoa phù hợp nhất, confidence từ 0.0 đến 1.0."""                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                    
          resp = client.chat.completions.create(                                                                                                                                                                                                                                                                    
              model="llama-3.3-70b-versatile",
messages=[{"role": "user", "content": prompt}],                                                                                                                                                                                                                                                       
              temperature=0.1,                                                                                                                                                                                                                                                                                      
              response_format={"type": "json_object"},                                                                                                                                                                                                                                                              
          )                                                                                                                                                                                                                                                                                                         
          import json
          data = json.loads(resp.choices[0].message.content)                                                                                                                                                                                                                                                        
          return data
      except Exception as e:                                                                                                                                                                                                                                                                                        
          print(f"[Phobert] Groq error: {e}, dùng fallback")
          return {"suggested_departments": keyword_fallback(req.text)}